### ISSUE TITLE
Port fixes from jasmine-flight

### ISSUE THREAD

**Issue by necolas** [flightjs/mocha-flight#3] opened 2013-07-25 17:44 UTC
- [ ] Fix null values causing validateHash to fail.
- [x] Fix setupComponent unnecessarily wrapping fixtures in a div.

**Comment by jared-stilwell** [comment] 2015-05-21 22:56
@necolas if the "Fix null values causing validateHash to fail." issue still exists, could you provide some detail on how to reproduce it?

**Comment by jared-stilwell** [comment] 2015-09-05 01:01
Closing this since I'm not sure what the first item in the description refers to.

**Closed by jared-stilwell** 2015-09-05 01:01 UTC
